### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#10]
I would like to point out that an identifier like "[`__PGCENTER_H__`](https://github.com/lesovsky/pgcenter/blob/6238e438d965393baafc502f90be6fd8e0a5ebc3/pgcenter.h#L6)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lesovsky** [comment]
Adjusted)) b606957, Thanks!
