### ISSUE TITLE
SIGQUIT when Duoble time \ is pressed. Or some :) (can't reproduce)

### ISSUE THREAD

**Issue by fuziko** [lesovsky/pgcenter#100]
Hello There!

Try to use it in my environment (ubuntu server 16.04 amd64) and PG 11
So in option tries (h - help me) i fond a symbol \  (or / symbol ))
When i press it i put in psql shell, but can't enter anything here.
So i press it again and got a SIGQUIT ..

Can't reproduce it.
Hope it helped .. if not just close - no matter!

> root@dlp:~# sudo -u postgres pgcenter top
> root@dlp:~# could not change directory to "/root": Permission denied
> psql (11.11 (Ubuntu 11.11-1.pgdg16.04+1), server 11.12 (Ubuntu 11.12-1.pgdg16.04+1))
> Type "help" for help.
> 
> postgres=# ^C
> postgres=# ^\SIGQUIT: quit
> PC=0x46d921 m=0 sigcode=128
> 
> goroutine 0 [idle]:
> runtime.futex(0xc20510, 0x80, 0x0, 0x0, 0x0, 0x7fffaed43000, 0x43ce59, 0xc0000a8d50, 0x7fffaed43008, 0x40c1ff, ...)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/sys_linux_amd64.s:579 +0x21
> runtime.futexsleep(0xc20510, 0xc000000000, 0xffffffffffffffff)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/os_linux.go:44 +0x46
> runtime.notesleep(0xc20510)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/lock_futex.go:159 +0x9f
> runtime.mPark()
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:1340 +0x39
> runtime.stoplockedm()
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:2451 +0x6e
> runtime.schedule()
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:3059 +0x48c
> runtime.park_m(0xc00020e180)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:3274 +0x9d
> runtime.mcall(0x0)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/asm_amd64.s:327 +0x5b
> 
> goroutine 1 [syscall]:
> syscall.Syscall6(0xf7, 0x1, 0x83bf, 0xc00010f640, 0x1000004, 0x0, 0x0, 0x3, 0x0, 0xc00010f690)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/syscall/asm_linux_amd64.s:43 +0x5
> os.(*Process).blockUntilWaitable(0xc0004c5860, 0x9, 0x9, 0x0)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/wait_waitid.go:32 +0x9e
> os.(*Process).wait(0xc0004c5860, 0xc00002602e, 0x946890, 0x946898)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/exec_unix.go:22 +0x39
> os.(*Process).Wait(...)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/exec.go:129
> os/exec.(*Cmd).Wait(0xc0003049a0, 0x0, 0x0)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/exec/exec.go:507 +0x65
> os/exec.(*Cmd).Run(0xc0003049a0, 0x4, 0xc00010f870)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/exec/exec.go:341 +0x5f
> github.com/lesovsky/pgcenter/top.runPsql.func1(0xc000216120, 0xc0001a2690, 0x7, 0xc00051c001)
>         /home/runner/work/pgcenter/pgcenter/top/psql.go:35 +0x25c
> github.com/jroimartin/gocui.(*Gui).execKeybindings(0xc000216120, 0xc0001a2690, 0xc00010fa10, 0x0, 0x0, 0x0)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:629 +0xc8
> github.com/jroimartin/gocui.(*Gui).onKey(0xc000216120, 0xc00010fa10, 0x0, 0x0)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:593 +0x1c5
> github.com/jroimartin/gocui.(*Gui).handleEvent(...)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:413
> github.com/jroimartin/gocui.(*Gui).consumeevents(0xc000216120, 0xc00010fb10, 0x0)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:395 +0x192
> github.com/jroimartin/gocui.(*Gui).MainLoop(0xc000216120, 0x946418, 0x9b5380)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:381 +0x1fa
> github.com/lesovsky/pgcenter/top.mainLoop(0x9b53b8, 0xc000138010, 0xc000180500, 0x0, 0x5)
>         /home/runner/work/pgcenter/pgcenter/top/ui.go:45 +0x225
> github.com/lesovsky/pgcenter/top.RunMain(0xc0001a2000, 0x0, 0x0)
>         /home/runner/work/pgcenter/pgcenter/top/top.go:30 +0x19b
> github.com/lesovsky/pgcenter/cmd/top.glob..func1(0xc19f20, 0xc4dd28, 0x0, 0x0, 0x0, 0x0)
>         /home/runner/work/pgcenter/pgcenter/cmd/top/top.go:31 +0xc5
> github.com/spf13/cobra.(*Command).execute(0xc19f20, 0xc4dd28, 0x0, 0x0, 0xc19f20, 0xc4dd28)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x472
> github.com/spf13/cobra.(*Command).ExecuteC(0xc1a180, 0xc0000a4778, 0xc000113f78, 0x406365)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
> main.main()
>         /home/runner/work/pgcenter/pgcenter/cmd/pgcenter.go:62 +0x31
> 
> goroutine 269 [select]:
> github.com/lesovsky/pgcenter/top.collectStat(0x9b5380, 0xc0003aa000, 0xc00012e840, 0xc000114360, 0xc000114300)
>         /home/runner/work/pgcenter/pgcenter/top/stat.go:59 +0x3f3
> github.com/lesovsky/pgcenter/top.doWork.func1(0x9b5380, 0xc0003aa000, 0xc000180500, 0xc000114360, 0xc00040e010)
>         /home/runner/work/pgcenter/pgcenter/top/ui.go:77 +0x5c
> created by github.com/lesovsky/pgcenter/top.doWork
>         /home/runner/work/pgcenter/pgcenter/top/ui.go:76 +0xeb
> 
> goroutine 5 [syscall]:
> os/signal.signal_recv(0x9b11b0)
>         /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/sigqueue.go:168 +0xa5
> os/signal.loop()
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/signal/signal_unix.go:23 +0x25
> created by os/signal.Notify.func1.1
>         /opt/hostedtoolcache/go/1.16.0/x64/src/os/signal/signal.go:151 +0x45
> 
> goroutine 40 [chan send, 1 minutes]:
> github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc000216090)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:354 +0x75
> created by github.com/jroimartin/gocui.(*Gui).MainLoop
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:352 +0x54
> 
> goroutine 338 [select]:
> github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
>         /home/runner/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20180819125858-b66b20ab708e/api.go:331 +0x217
> github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc000216120)
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:354 +0x30
> created by github.com/jroimartin/gocui.(*Gui).MainLoop
>         /home/runner/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:352 +0x54
> 
> rax    0xca
> rbx    0xc203c0
> rcx    0x46d923
> rdx    0x0
> rdi    0xc20510
> rsi    0x80
> rbp    0x7fffaed42fd0
> rsp    0x7fffaed42f88
> r8     0x0
> r9     0x0
> r10    0x0
> r11    0x286
> r12    0xc0002017a4
> r13    0x0
> r14    0x1
> r15    0x1
> rip    0x46d921
> rflags 0x286
> cs     0x33
> fs     0x0
> gs     0x0

- OS: [output of `cat /etc/os-release`]

support@dlp:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- pgCenter Version [output of `pgcenter --version`]

support@dlp:~$ sudo -u postgres pgcenter --version
pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release

- pgCenter installation method: [releases page, manual build, other?]

install from DEB-package via dpkg -i

- PostgreSQL Version [output of `psql -c 'select version()'`]

support@dlp:~$ sudo -u postgres psql
psql (11.11 (Ubuntu 11.11-1.pgdg16.04+1), server 11.12 (Ubuntu 11.12-1.pgdg16.04+1))

**Comment by lesovsky** [comment]
Hmm, it sounds a bit strange:
- key `\` is not processed by pgcenter (ignored).
- key '/' is not used for calling psql and is used for searching patterns. If you were in psql, it means the `~` key was pressed. 
- when you are in psql, both types of slashes are considered as usual text and not exit from psql (ctrl+C or ctrl+D are used for exit)

> So i press it again and got a SIGQUIT ..

SIGQUIT is a signal, it could be sent by other process or by user using `kill` utility. 

**Did not you try to send SIGQUIT to psql using `kill -SIGQUIT ...`?** In this case it is possible to make a mistake in PID and accidentally specify pgcenter's PID and get behavior similar to described issue.

**Comment by lesovsky** [comment]
It seems you pressed `Ctrl + \` combination:

> Ctrl+\ Closely related to Ctrl+C is the Ctrl+\ shortcut. It basically sends the SIGQUIT signal which will the process to terminate and dump core.
