### ISSUE TITLE
Why 0.8.0 & 0.9.1 shows /32 CIDR network mask for connected clients?

### ISSUE THREAD

**Issue by AndreyKopeyko** [lesovsky/pgcenter#103]
**Describe the bug**
In 'activity' and 'replication' modes the /32 network mask is shown for every IPv4 client connected - it's obvious, useless and just grabs 3 symbols positions from other useful information. It's well-known "feature\bug" on pgcenter - you have to use wide terminals to operate it.
![screenshot-2021-07-20-21-08-53](https://user-images.githubusercontent.com/10827221/126378596-f22fac3a-03fb-488b-b45a-5cc30c7517a7.png)
![screenshot-2021-07-20-21-20-27](https://user-images.githubusercontent.com/10827221/126379123-b6c336c7-6467-4b5e-aa40-862bc8c7554b.png)

**Environment**
Describe the environment where the bug occurred.
- OS: CentOS Linux 7 (Core)
- Docker image name and tag (in case of Docker-related environment)  
- 
     pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release
pgcenter v0.9.1 9d19b164f6912cf057b2998a91c5822f8201af13-release
- pgCenter installation method: RPM package released
- PostgreSQL Version: PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (R
ed Hat 4.8.5-44), 64-bit
- Did you try build pgCenter from master branch and reproduce the issue? 'no'

**To Reproduce**
just run pgcenter

**Expected behavior**
No CIDR mask should be shown at all.

**Comment by lesovsky** [comment]
The netmask is added by postgres driver implicitly during conversion from inet type to text.
Thank for report, will fix this in next release.

**Comment by lesovsky** [comment]
Fixed in master branch, will appear in next minor or patch release.
