### ISSUE TITLE
run stuck with ERROR: pg_stat_statements must be loaded via shared_preload_libraries (SQLSTATE 55000) | only extension created

### ISSUE THREAD

**Issue by grin31** [lesovsky/pgcenter#104]
run pgcenter stuck with error
`ERROR: pg_stat_statements must be loaded via shared_preload_libraries (SQLSTATE 55000)`

pg_stat_statement present in extensions

```
[local]:5432 postgres@postgres=# \dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+------------------------------------------------------------------------
 pageinspect        | 1.8     | public     | inspect the contents of database pages at a low level
 pg_stat_statements | 1.8     | public     | track planning and execution statistics of all SQL statements executed
 pgstattuple        | 1.5     | public     | show tuple-level statistics
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(4 rows)
```

but not load in shared_preload_libraries

```
[local]:5432 postgres@postgres=# show shared_preload_libraries ;
 shared_preload_libraries
--------------------------
(0 row)
```

```
[local]:5432 postgres@postgres=# select * from pg_stat_statements;
ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
```

**Comment by NikolayS** [comment]
@grin31 You need to adjust PostgreSQL configuration -- the fact that it's present in available extensions doesn't mean that the library was loaded. Two ways to solve:
1. Edit PostgreSQL.conf
2. ALTER SYSTEM

Then restart is required.

**Comment by grin31** [comment]
@NikolayS my workaround is:
`drop extension pg_stat_statements;`
in all databases

**Comment by lesovsky** [comment]
You have rare and useless configuration - `pg_stat_statements` extension installed in a database and empty `shared_preload_libraries`. As mentioned above you have two ways - enable pg_stat_statements in shared_preload_libraries and restart Postgres server, or drop extension.

Anyway, I will add proper checking of pg_stat_statements and fix this stuck. Thanks for report.

**Comment by lesovsky** [comment]
Fixed in master branch, will appear in next minor or patch release.
