### ISSUE TITLE
way to specify host, user and db via environment variables

### ISSUE THREAD

**Issue by fahadshery** [lesovsky/pgcenter#108]
Hi,

I would rather setup this container over `Kubernetes`.

Is there a way or will there be an option of setting up this container by specifying the `postgres host`, `user/password` and `database` via `environment variables`? 
This will make it very easy for us to manage and point the same `container` to different `postgres servers` if required.

Thanks for a great project.
Cheers,

**Comment by lesovsky** [comment]
Hi,

pgcenter supports [libpq](https://www.postgresql.org/docs/current/libpq-envars.html) environment variables such as PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD.

Closed, because not a bug :)
