### ISSUE TITLE
reset postgresql statistics counters failed

### ISSUE THREAD

**Issue by anesheret** [lesovsky/pgcenter#109]
**Description**
When i press 'Q' to reset postgresql statistics, i get error
```
Reset statistics failed: template: query:1:9: executing "query" at <.PgSSSchema>: can't evaluate field PgSSSchema in type query.Options
```
**Environment**
Describe the environment where the bug occurred.
- OS: [output of `cat /etc/os-release`]
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- pgCenter Version [output of `pgcenter --version`]
```
pgcenter v0.9.2 7ebd54847cbbf72a98cbde39e9afc3845cba9839-release
```
- pgCenter installation method: [releases page, manual build, other?]
```
dpkg -i <dep file downloaded from github release page>
```
- PostgreSQL Version [output of `psql -c 'select version()'`]
```
PostgreSQL 14.1 (Ubuntu 14.1-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
```
- Did you try build pgCenter from master branch and reproduce the issue? ['yes' or 'no']
```
no
```
**To Reproduce**
Press 'Q' in pgcenter top `<dbname>`
**Expected behavior**
Reset statisticts should be done w/o errors.

**Additional context**
Error occurred only if i run pgcenter top with database other that postgres.

**Comment by lesovsky** [comment]
Looks like a problem with detecting pg_stat_statements.

Please connect to database using psql and show the output of:
- `\dn` command
- `\dx` command
- `show shared_preload_libraries;`

**Comment by anesheret** [comment]
Yes, pg_stat_statements is installed and worked fine.
as you requested:

- \dn
```
icompany=# \dn
  List of schemas
  Name  |  Owner   
--------+----------
 public | postgres
(1 row)
```
- \dx
```
icompany=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
 pg_buffercache     | 1.3     | public     | examine the shared buffer cache
 pg_stat_statements | 1.9     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgres_fdw       | 1.1     | public     | foreign-data wrapper for remote PostgreSQL servers
(4 rows)
```

**Comment by lesovsky** [comment]
Thanks for report, fixed in master branch.
