### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#11]
The functions "[endwin](http://pubs.opengroup.org/onlinepubs/007908775/xcurses/endwin.html)" and "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" do not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[sig_handler](https://github.com/lesovsky/pgcenter/blob/d693f7d8f58a102996bde7644caf557ae2c7a0e9/pgcenter.c#L69)".

**Comment by lesovsky** [comment]
I have some troubles here, may be you have ideas how to do this correctly?
I think exit() may be replaced with _Exit(), but what to do with endwin()? It's a ncurses function and I have no replacements for this function.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")

**Comment by lesovsky** [comment]
pgcenter has been rewritten using Go, I think this issue is not actual now, but you can reopen it and point to particular problems.
