### ISSUE TITLE
Unable to upgrade from 0.4 to 0.9 at Centos8

### ISSUE THREAD

**Issue by wasiualhasib** [lesovsky/pgcenter#113]
I installed pgcenter version 0.4.0. Unable to upgrade from 0.4 to 0.9  at Centos8  using 
`yum install pgcenter. `

How can I install latest version at PostgreSQL 14 where linux OS is Centos8?  

**bug***
I found some bug at this version. Sometimes all feature not working such as without any warning message exit. 
May I know the reason behind this?

**Comment by lesovsky** [comment]
0.4.0 is too old, highly likely all bugs found in this version has been fixed.
Recent version could be downloaded from [releases](https://github.com/lesovsky/pgcenter/releases) page
