### ISSUE TITLE
appname field is trimmed to 16 chars

### ISSUE THREAD

**Issue by AndreyKopeyko** [lesovsky/pgcenter#117]
**Describe the bug**
Only first 16 characters of "application_name" connection parameter, set by pgbouncer, are shown at activity screen in "appname" column. Expanding this column does not helps to see full value of the string.
![Снимок экрана от 2022-07-21 14-16-53](https://user-images.githubusercontent.com/10827221/180209056-8d6a4e11-d22e-4d12-bcb4-dafd843f46ab.png)

**Environment**
Describe the environment where the bug occurred.
- OS: CentOS Linux 7 (Core)
- Docker image name and tag: none
- pgCenter Version: v0.9.2 (7ebd54847cbbf72a98cbde39e9afc3845cba9839, release)
- pgCenter installation method: releases page
- PostgreSQL Version: 13.6
- Did you try build pgCenter from master branch and reproduce the issue? no

**To Reproduce**
1. connect to PGSQL via pgbouncer with "application_name_add_host = 1"
2. run pgcenter and expand "appname" column

**Expected behavior**
I want to see IPv4 address:port as pgbouncer have set it.

**Comment by lesovsky** [comment]
Hi, fixed [there](https://github.com/lesovsky/pgcenter/commit/9f09649274d08e16dc734b23e85e6bdaac7b400b), will apear in next release.
