### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#12]
Would you like to add more error handling for return values from functions like the following?
- [fscanf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fscanf.html) ⇒ [get_loadavg](https://github.com/lesovsky/pgcenter/blob/d693f7d8f58a102996bde7644caf557ae2c7a0e9/pgcenter.c#L888)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [password_prompt](https://github.com/lesovsky/pgcenter/blob/d693f7d8f58a102996bde7644caf557ae2c7a0e9/pgcenter.c#L267)

**Comment by lesovsky** [comment]
Fixed (b606957). Thanks!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Are there [a few update candidates](https://github.com/lesovsky/pgcenter/blob/b60695729e43f7ad475e2e0a90e8c84e78a3c240/pgcenter.c#L649 "Update candidate: open_connections()") left over?

**Comment by lesovsky** [comment]
Hi,
check 0a26b5c4a0b3da99b2877f308e8bdec14e96cc9b, is there any dangerous sections?
I've replaced strcpy/strcat with strncpy and snprintf.

**Comment by lesovsky** [comment]
Hi, 
check c1af556cb1d09eefb67423139f246c1bbd860311, all raw numbers replaced with macros.

**Comment by lesovsky** [comment]
Hi,
check 4a2b7387e9581eff14690b96521d721c78d3b63d
There are:
  * use unsigned data types for always positive variables.
  * stdout sanity check in password_prompt().
  * use sizeof(...) instead of macros.
  * strrpl() fix.

**Comment by elfring** [comment]
Is [the function "print_log" another update candidate](https://github.com/lesovsky/pgcenter/blob/ce53dd666e0d98f70e35af3f708c5c447e1320b3/pgcenter.c#L4023 "Checking lseek() in print_log()?")?

**Comment by lesovsky** [comment]
What is wrong there?

**Comment by elfring** [comment]
I recommend to [care also for return values from calls of the function "lseek"](http://pubs.opengroup.org/onlinepubs/9699919799/functions/lseek.html "Move the file offset").

**Comment by lesovsky** [comment]
Yes, lseek is a good candidate, are there any calls which should be checked?

**Comment by elfring** [comment]
Yes. - There are more function calls left over for further considerations.

* Should Curses functions like "wclear" and "wprintw" also be checked consistently?
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?

  How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by lesovsky** [comment]
Yes, it's generally good idea.

**Comment by elfring** [comment]
I would appreciate another constructive feedback for this issue.

**Comment by lesovsky** [comment]
pgcenter has been rewritten using Go, I think this issue is not actual now, but you can reopen it and point to particular problems.
