### ISSUE TITLE
ERROR: pg_stat_statements must be loaded via shared_preload_libraries

### ISSUE THREAD

**Issue by sanjaymadari** [lesovsky/pgcenter#120]
What I have done...
 - Created pg_stat_statements extentions with following query 
```
CREATE EXTENTION pg_stat_statements
```

- Enabled following in postgresql.conf file
```
shared_preload_libraries = 'pg_stat_statements'
```

- Restarted postgres service with following command
```
brew services restart postgresql
```

- Tried to run the following command and then go error.
```
SELECT * FROM pg_stat_statements;
ERROR: pg_stat_statements must be loaded via shared_preload_libraries
```

Note: This error was occured in Macbook Pro M1 chip.

Gone through following issues and checked for solutions and nothing is worked for me.
https://github.com/powa-team/pg_stat_kcache/issues/18
https://github.com/lesovsky/pgcenter/issues/104

**Comment by lesovsky** [comment]
This is not a bug of pgcenter. The error points your have to configure pg_stat_statements properly. Follow the official [documentation](https://www.postgresql.org/docs/current/pgstatstatements.html) and read it carefully.
