### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#15]
Would you like to replace more defines for constant values like [`REP_…`](https://github.com/lesovsky/pgcenter/blob/c142055f239f2fa33aa58347b39136c397bc7658/qstats.h#L89 "Report selection") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Enumerated types in C") to stress their relationships?

**Comment by lesovsky** [comment]
Good idea, thanks! (b606957)
