### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#16]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/lesovsky/pgcenter/blob/0302d8399b5a0bba788fff7f9c5d3de52944a0cb/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by lesovsky** [comment]
Thanks, it may be possible in near future.
