### ISSUE TITLE
segfault when switching to activity mode

### ISSUE THREAD

**Issue by TobWen** [lesovsky/pgcenter#17]
As you've already warned in readme, segfauls might appear.
Most of the time, I want to switch to 'a' activity mode, I'm getting a segfault.

Which information do you need to fix the problem?

My system:´´´Linux tobwen 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14) x86_64 GNU/Linux´´´

My PostgreSQL: ```9.4.5-0+deb8u1 ```

**Comment by lesovsky** [comment]
Hi,
1. Build pgcenter from latest sources (with make).
2. Enable coredump with ```ulimit -c unlimited```
3. Reproduce segafult (after pgcenter crash, core dump will be created in current dir).
4. Run pgcenter with gdb ```gdb ./pgcenter <coredump>```
5. In gdb console, run "where" command, and show me latest 15 lines.

**Comment by TobWen** [comment]
```<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pgcenter...done.
[New LWP 20125]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `pgcenter -d gis -U postgres'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f020b8e8ff6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) where
#0  0x00007f020b8e8ff6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x000000000040b135 in sort_array (res_arr=0xcee150, n_rows=7, n_cols=11, screen=0xbc7890) at pgcenter.c:2261
#2  0x0000000000412bed in main (argc=5, argv=0x7fff090ed618) at pgcenter.c:4792
(gdb)```

**Comment by lesovsky** [comment]
Try build 43dc524.

**Comment by TobWen** [comment]
https://github.com/lesovsky/pgcenter/commit/43dc524f2f48eb98285d52a3d976c3281c6b8886 seems to work well.

Good work.
