### ISSUE TITLE
Error when calling make

### ISSUE THREAD

**Issue by rpacheco-aa** [lesovsky/pgcenter#18]
Ubuntu 12.04 LTS, Postgres 9.2 running on the latest vagrant:

vagrant@precise64:~$ git clone https://github.com/lesovsky/pgcenter
Cloning into 'pgcenter'...
remote: Counting objects: 861, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 861 (delta 1), reused 0 (delta 0), pack-reused 853
Receiving objects: 100% (861/861), 344.22 KiB | 292 KiB/s, done.
Resolving deltas: 100% (438/438), done.
vagrant@precise64:~$ cd pgcenter
vagrant@precise64:~/pgcenter$ make
cc -g -std=gnu99 -Wall -pedantic  -I/usr/include/postgresql  -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -o pgcenter pgcenter.c -lpq -lncurses -ltinfo -lmenu
pgcenter.c:15:18: fatal error: menu.h: No such file or directory
compilation terminated.
make: *** [pgcenter] Error 1
vagrant@precise64:~/pgcenter$

**Comment by lesovsky** [comment]
Hi, 
install libncurses5-dev package.
