### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by NikolayS** [lesovsky/pgcenter#2]
```
nikolay@dev:~/github$ cd pgcenter/
nikolay@dev:~/github/pgcenter$ make
gcc -g -std=gnu99 -Wall -pedantic -I/usr/include/postgresql -L/usr/lib/x86_64-linux-gnu -o pgcenter pgcenter.c -lncurses -ltinfo -lpq
pgcenter.c:11:21: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
                     ^
compilation terminated.
Makefile:25: recipe for target 'pgcenter' failed
make: *** [pgcenter] Error 1
nikolay@dev:~/github/pgcenter$ uname -a
Linux dev 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2 (2015-07-17) x86_64 GNU/Linux
```

**Comment by lesovsky** [comment]
Check that the ncurses devel package installed.
If installed:
1. what OS you use?

**Comment by NikolayS** [comment]
It's Debian.
`sudo apt-get install ncurses-dev` solved the issue.
Another one:
![screenshot 2015-08-24 16 03 21](https://cloud.githubusercontent.com/assets/1345402/9440685/ad4cf312-4a79-11e5-9bcb-474e6bd66661.png)

I run at under `postgres` user, where`psql` works w/o password (double-checked it).
I checked your readme, and cannot find any directions how to set up usr/pwd params for pgcenter.

**Comment by NikolayS** [comment]
OK, I guessed that it has the same options as `psql` does :) 
Maybe it's worth mentioning in readme.
I'm closing the issue.

**Comment by NikolayS** [comment]
(and maybe it's a good idea to allow working w/o password -- in case when psql works without it)

**Comment by NikolayS** [comment]
Reopening.. It cannot connect even when I run it like this:
```
pgcenter -U username dbname -W
```
 - strange that without `-W` it doesn't ask for password
 - even with password, it still cannot connect.

Postgres version is 9.4.3.

**Comment by lesovsky** [comment]
See path specified in unix_socket_directories in postgresql.conf, and try "-h path"

**Comment by NikolayS** [comment]
Ahrrr, adding `-h localhost` solved the issue.

**Comment by lesovsky** [comment]
The problem is that the postgres pkg developers use different default host in psql. RHEL uses /tmp, Debian uses /var/run/postgresql. pgCenter uses RHEL way. And Debian/Ubuntu users may have problem here.

![different-host](https://cloud.githubusercontent.com/assets/953312/9441037/1513b1a8-4a8d-11e5-84f6-b663107761e8.png)

I think how to solve this issue with elegant way.

**Comment by lesovsky** [comment]
try a935265d7d44bf2f97d5ba85433ff44eba8b9b9b

**Comment by NikolayS** [comment]
Works w/o pwd now, thanks
