### ISSUE TITLE
Support standard postgres environment variables

### ISSUE THREAD

**Issue by soulrebel** [lesovsky/pgcenter#20]
Most postgres tools (pg_dump, psql) are happy with the same set of environment variables and this is how people (I for one) got used to control them.

Ref: http://www.postgresql.org/docs/current/static/libpq-envars.html

cheers

**Comment by lesovsky** [comment]
Ok, added in todo-list.

**Comment by lesovsky** [comment]
Done, check out fcb7b69ac396dc19cf5d8190b2d37ed6a4b3d3f8.
Pardon, for it is so late.

**Comment by soulrebel** [comment]
that's great! will try!
