### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#22]
I suggest to add the key word "const" to the type specifiers for parameters like the following.
* progname (function "[print_title](https://github.com/lesovsky/pgcenter/blob/4a2b7387e9581eff14690b96521d721c78d3b63d/pgcenter.h#L777)")
* s_string, r_string (function "[strrpl](https://github.com/lesovsky/pgcenter/blob/4a2b7387e9581eff14690b96521d721c78d3b63d/pgcenter.h#L831)")

Would you like to apply the advices from [an article](https://en.wikipedia.org/wiki/Const_(computer_programming)#Consequences "const-correctness") to more places in your source files?

**Comment by lesovsky** [comment]
Ok, accepted.

**Comment by lesovsky** [comment]
Could you check fb225cabdb5083c596698100ce213f5482e990be.
