### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#23]
How do you think about to benefit from [parallel build trees](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html "Parallel build trees (VPATH)") also for this software?
Would you like to [support out-of-source](https://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F "Out-of-source build trees") ([VPATH](https://www.gnu.org/software/make/manual/html_node/General-Search.html "Search path for prerequisites")) builds?

**Comment by lesovsky** [comment]
I think no, what reasons to use that?

**Comment by elfring** [comment]
* Will your software evolve in the way eventually that several modules will be used (instead of [a single source file](https://github.com/lesovsky/pgcenter/blob/fb225cabdb5083c596698100ce213f5482e990be/pgcenter.c "Main source file") so far)?
* Would you like to support an other software build structure?

**Comment by lesovsky** [comment]
May be in the future, but this is low priority task.
No, current model work fine, and there are no urgent reasons to change it.
