### ISSUE TITLE
Safe setting of "ESCDELAY"

### ISSUE THREAD

**Issue by elfring** [lesovsky/pgcenter#24]
It is tried to [set the variable "`ESCDELAY`"](https://github.com/lesovsky/pgcenter/blob/fb225cabdb5083c596698100ce213f5482e990be/pgcenter.c#L4672 "Configuration for Curses") directly.
How do you think about to [use the function "`set_escdelay`"](http://linux.die.net/man/3/set_escdelay "Curses thread support") instead?

**Comment by lesovsky** [comment]
I didn't knew about set_escdelay, thank you.

**Comment by lesovsky** [comment]
Done ce53dd666e0d98f70e35af3f708c5c447e1320b3.
