### ISSUE TITLE
Fix for ncurses6

### ISSUE THREAD

**Issue by devrimgunduz** [lesovsky/pgcenter#25]
Hi,

To build pgcenter RPMs on Fedora 23+, I added the following patch so that it detects ncurses 6. It may be good to add this upstream:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.6/pgcenter/EL-6/pgcenter-makefile.patch;h=d904e8fe0b57b5bcf7e16a4cdbf36f56ed4a1f54;hb=61f8fe2d62127379ec3cd698fae2647959233142

Thanks!

**Comment by lesovsky** [comment]
Hi,

Thanks, I'll check it. Need to be sure that's will work correctly on the other distribs, on Debian-family particularly.

**Comment by tigerfoot** [comment]
Strangely it seems to have been added with  b5245caa ?
Tested on openSUSE seems to work pgCenter is linked to ncurse6

**Comment by lesovsky** [comment]
I checked how it's built on Fedora 24 and it's already done with b5245ca. But there is an issue with RHEL-specific paths, like "/usr/pgsql-x.y/bin", so I've made a few changes in Makefile (322fda3bac40097b250551307c6428f8bf487df7).
