### ISSUE TITLE
pgcenter RPM availability

### ISSUE THREAD

**Issue by devrimgunduz** [lesovsky/pgcenter#26]
Hi,

pgcenter RPMs are available in PostgreSQL YUM repository: https://yum.postgresql.org . Can you please update to reflect this? Packages are available for RHEL 6, RHEL 7, and Fedora 23+

Thanks!

Regards, Devrim

**Comment by lesovsky** [comment]
Wow, it's a big and nice surprise for me. Thanks!
I've updated information in the README, and also make new 0.3.0 release.

Regards, Alexey

**Comment by devrimgunduz** [comment]
Thank you!
