### ISSUE TITLE
pgcenter.c:2372]: (error) Buffer is accessed out of bounds: msg

### ISSUE THREAD

**Issue by dcb314** [lesovsky/pgcenter#27]
Source code is

    snprintf(msg, 128, "Set filter, current: \"%s\": ", ctx.fstrings[ctx.order_key]);

Maybe better code

    snprintf(msg, S_BUF_LEN, "Set filter, current: \"%s\": ", ctx.fstrings[ctx.order_key]);

**Comment by lesovsky** [comment]
Ouch, my fault.

fixed now (f10d10d), thanks!
