### ISSUE TITLE
Incorrect sorting on some columns

### ISSUE THREAD

**Issue by eranthis** [lesovsky/pgcenter#29]
...like avg_t, avg_self_t. The columns are sorted as text, not as a number.

![img-2016-10-25-15-31-23](https://cloud.githubusercontent.com/assets/2877613/19686851/bf898d80-9acb-11e6-9242-bd3329161121.png)

**Comment by lesovsky** [comment]
Thanks, check out 492439d6ba567e8e517ea69cdb42f90a078f011f
Pardon my tardiness.
