### ISSUE TITLE
shouldn't show cpu/io stats when not on db host

### ISSUE THREAD

**Issue by seamusabshere** [lesovsky/pgcenter#30]
if you connect to a remote db host, it's confusing to show cpu/io stats (because they are not real)

this could either be auto-detected or use a commandline flag

**Comment by lesovsky** [comment]
Hi,
It's not a bug, this described in "Recommendations" section in README. Unfortunately, there is no simlpe way to get cpu/memory/disk/etc usage from remote hosts through postgres connection.

**Comment by seamusabshere** [comment]
@lesovsky that's why i'm saying you should _hide_ the stats if they are not real

**Comment by lesovsky** [comment]
It seems to me very ugly, that the part of an interface (top-left corner) will shown as a black square. Or could you propose a more elegant way?

**Comment by seamusabshere** [comment]
i think that is the right solution, even if it is a bit ugly... you could write `[cpu/io stats disabled because remote]`

**Comment by lesovsky** [comment]
Ok, I think about it. But currently I looking for a convenient way to get /proc/* stats through pg connection. If I failed, I will make as you propose.

**Comment by seamusabshere** [comment]
oh, that's cool! like a fdw?

**Comment by lesovsky** [comment]
yep, file_fdw theoretically is the most attractive way.
