### ISSUE TITLE
support OS X

### ISSUE THREAD

**Issue by slotrans** [lesovsky/pgcenter#32]
This is what I get trying to build pgcenter on OS X 10.10.5:
$ make
cc -g -std=gnu99 -Wall -pedantic  -I/usr/local/Cellar/postgresql/9.5.4_1/include  -L/usr/local/lib -o pgcenter pgcenter.c -lpq -lncurses -lmenu
pgcenter.c:13:10: fatal error: 'linux/types.h' file not found
#include <linux/types.h>
         ^
1 error generated.
make: *** [pgcenter] Error 1

**Comment by lesovsky** [comment]
Hi,
I guess linux-specific header file is absent under OS X (which isn't linux-based). I've workaround for this problem, but I don't have OS X, so I can't test it.

I leave the issue as opened, maybe my friends give me a temp access to their macs :)

**Comment by lesovsky** [comment]
Also I've accepted pull-request with Dockerfile, you can try pgcenter with docker.

**Comment by hamin** [comment]
@lesovsky i have a mac :). Happy to test for you. If it works out would be great to add a homebrew formula for pgcenter

**Comment by muminoff** [comment]
> add a homebrew formula

👍

**Comment by lesovsky** [comment]
@hamin can you only test (exec instructions provided by me) or can give me a ssh access? First way is longer and second is preferred for me because I can't estimate amount and complexity of work.

**Comment by lesovsky** [comment]
Good news, I've found that OS X can run under Qemu/KVM, so there is no need to get an access to real OS X.

**Comment by muminoff** [comment]
@lesovsky can't wait for an homebrew formula, keep up the good work!

**Comment by lesovsky** [comment]
I've started OS X under VmWare and have bad news for you guys. Some stats features in current pgcenter rely on _procfs_ pseudo-fs which is absent on OS X, so pgcenter is unable to run directly from OS X. I'd recommend to use docker.

**Comment by hamin** [comment]
@lesovsky I see. I'm happy to give this a shot to see what equivalent proofs features on OS X that would allow pgcenter to work. Did you have a solution/thoughts to replace these headers? :

```
#include <linux/types.h>
#include <linux/ethtool.h>
#include <linux/sockios.h>
```

Feel free to keep this issue closed btw. I work on mac so was just thinking of giving this a fair shot...maybe I'll learn something new :)

**Comment by lesovsky** [comment]
I don't familiar with OS X and its internals and I have no clue how to replace the headers. (((
