### ISSUE TITLE
Centos 7 casue swap

### ISSUE THREAD

**Issue by liuqian1990** [lesovsky/pgcenter#33]

**Comment by liuqian1990** [comment]
Centos 7 casue swap

**Comment by liuqian1990** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                 
   44 root      20   0       0      0      0 D  37.7  0.0   0:05.85 kswapd0                                                                                                                 
 2843 postgres  20   0 4208808 790320     40 D  19.3 77.8   0:05.06 pgcenter

**Comment by liuqian1990** [comment]
[postgres@localhost nodes]$ pgcenter -p 5433
Killed

**Comment by liuqian1990** [comment]
strace pgcenter -p 5433
brk(0x40e82000)                         = 0x40e82000
brk(0)                                  = 0x40e82000
brk(0x40ea3000)                         = 0x40ea3000
brk(0)                                  = 0x40ea3000
brk(0x40ec4000)                         = 0x40ec4000
brk(0)                                  = 0x40ec4000
brk(0x40ee5000)                         = 0x40ee5000
brk(0)                                  = 0x40ee5000
brk(0x40f06000)                         = 0x40f06000
brk(0)                                  = 0x40f06000
brk(0x40f27000)                         = 0x40f27000
brk(0)                                  = 0x40f27000
brk(0x40f48000)                         = 0x40f48000
brk(0)                                  = 0x40f48000
brk(0x40f69000)                         = 0x40f69000
brk(0)                                  = 0x40f69000
brk(0x40f8a000)                         = 0x40f8a000
brk(0)                                  = 0x40f8a000
brk(0x40fab000)                         = 0x40fab000
brk(0)                                  = 0x40fab000
brk(0x40fcc000)                         = 0x40fcc000
brk(0)                                  = 0x40fcc000
brk(0x40fed000)                         = 0x40fed000
brk(0)                                  = 0x40fed000
brk(0x4100e000)                         = 0x4100e000
brk(0)                                  = 0x4100e000

**Comment by lesovsky** [comment]
Hi,
1. how much RAM is available on this host?
2. do you have pg_stat_statements enabled and what settings are used **OR** is this problem occurs on pg_stat_statements stats (*x* and *X* hotkeys)?

I suppose there is an issue with a lot of quite long queries in pg_stat_statements with length more than 1kB.
