### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by kotsachin** [lesovsky/pgcenter#34]
Hi,

Can i get historical data using this tool ? If yes, How? Please send document link if available.

Regards,
Sachin

**Comment by lesovsky** [comment]
Hi, 
currently it's not implemented, but work in progress. I think it will be in next release.

**Comment by kotsachin** [comment]
Thanks for reply. 

As a small suggestion i would like if stats dump into small text files and parsed whenever required will be best option. dumping historical data again into database will be overhead again. It is better if user able to make any patters from historical data in graphical form.

Eager to see you next release with many new features .

**Comment by lesovsky** [comment]
Hmmm, but wait I didn't mention about I want to save stats into the database )))

**Comment by dan-aksenov** [comment]
Aany update on this. I could really use history feature.

**Comment by lesovsky** [comment]
yep, it developed in devel branch (and not published yet), there are some basic functions like recording and reporting basic stats about databases and tables, so further works will be related to adding other stats views. But this is not the primary target of the next release, and i have other features that i'd want to implement and test ))

**Comment by lesovsky** [comment]
released in v0.5.0
