### ISSUE TITLE
PostgreSQL 10 support: ERROR: function pg_current_xlog_location() does not exist

### ISSUE THREAD

**Issue by opusmagnum** [lesovsky/pgcenter#37]
Hi,
first of all -- thank you for the great tool, we have successfully used it with PostgreSQL 9.6. After upgrade to version 10.0, click on 'r' replication returns an error:
`ERROR: function pg_current_xlog_location() does not exist`

I assume, the reason for it is -- function pg_current_xlog_location is renamed to pg_current_wal_lsn. More about new function names -- https://wiki.postgresql.org/wiki/New_in_postgres_10#Renaming_of_.22xlog.22_to_.22wal.22_Globally_.28and_location.2Flsn.29 

Can you please look into it? Thanks in advance.

**Comment by lesovsky** [comment]
Hi
it's already fixed in 0a603f9 and will be automatically available in next release. Also you can build it directly from sources.
