### ISSUE TITLE
FATAL: ERROR:  column "deadlocks" does not exist

### ISSUE THREAD

**Issue by atomyuk** [lesovsky/pgcenter#4]
FATAL: ERROR:  column "deadlocks" does not exist
LINE 1: ...dates, tup_deleted AS deletes,         conflicts, deadlocks,...

**Comment by lesovsky** [comment]
it's already fixed in 2c056b928dfe7218b72b34bd720f6b7ef53cb4c9. install pgcenter from latest commit.
