### ISSUE TITLE
Should I create pgcenter database?

### ISSUE THREAD

**Issue by ethanhexd** [lesovsky/pgcenter#41]
When I run pgcenter,something is wrong.
I check pglog,found some error such as :

ERROR: relation "pgcenter.sys_proc_diskstats" does not exist
Statement: SELECT count(1) FROM pgcenter.sys_proc_diskstats
AND
Statement: SELECT count(1) FROM pgcenter.sys_proc_netdev,etc.

**Comment by ethanhexd** [comment]
PostgreSQL version is :11beta2

**Comment by lesovsky** [comment]
Hi,
no, you don't need to create dedicated `pgcenter` database. Maximum you need to create stats schema for pgcenter. It can be done by pgcenter itself, see `--install` parameter in usage. 

The metioned error tells about you about that pgcenter is connected to postgres on remote host and it tries to get system stats through pgcenter's sql functions. Try to install required schema and errors will disappear.
