### ISSUE TITLE
Can not install stats schema and functions into the database.

### ISSUE THREAD

**Issue by ethanhexd** [lesovsky/pgcenter#42]
------------>command:
pgcenter -h localhost -p 5432 -U xdb -d testdb -i

------------>Message return:
INFO: installing stats schema into xdb@localhost:5432/testdb
ERROR: install stats schema into xdb@localhost:5432/testdb failed:
ERROR: Can't locate Linux/Ethtool/Settings.pm in @INC (@INC contains: /root/perl5/lib/perl5 /usr/local/lib64/perl5 /usr/local/s

**Comment by lesovsky** [comment]
You should install perl module `Linux::Ethtool::Settings` into your system.
