### ISSUE TITLE
When the pgcenter is started, temporary files are generated.

### ISSUE THREAD

**Issue by vitabaks** [lesovsky/pgcenter#43]
Hi!
On some databases, when the pgcenter is started, temporary files are generated.

LOG:  **temporary file**: path "base/pgsql_tmp/pgsql_tmp112190.57", size 26511854
2018-09-06 15:49:14 MSK 5b912212.1b63e [112190-116] [local] postgres@mydb STATEMENT:  SELECT (sum(total_time) / sum(calls))::numeric(20,2) AS avg_query, sum(calls) AS total_calls FROM pg_stat_statements

- - - - - - -
work_mem = 512MB
PostgreSQL 9.4

**Comment by lesovsky** [comment]
Hi,
pgcenter tries to set its own setting for work_mem [here](https://github.com/lesovsky/pgcenter/blob/master/src/pgf.c#L55), and it's 32MB .
That is why your 512MB is ignored(((

Try to comment mentioned code (or increase work_mem value in  `PG_INCREASE_WORK_MEM_QUERY`), build the program and change work_mem on postgres side (it can be done globally via postgresql.conf, or per-user using `ALTER ROLE ... SET work_mem TO ...`)

I used to think that was a right way, especially for users who don't familiar with work_mem... I thought something like "default work_mem is too low, so why don't increase at program startup?". But now I think using predefined work_mem, end-user looses in flexibility in way to change work_mem for pgcenter in postgres. So probably I will change this code a bit.. adjust work_mem if it's too low and leave as-is if high.

**Comment by vitabaks** [comment]
I increased the value "work_mem " in the file \src\include\queries.h

> /* set work_mem for pg_stat_statements queries */
#define PG_INCREASE_WORK_MEM_QUERY "SET work_mem TO '512MB'"

Thank you!
