### ISSUE TITLE
Error Can't locate Linux/Ethtool/Settings.pm

### ISSUE THREAD

**Issue by emartinezff** [lesovsky/pgcenter#48]
Regards

when I try to configure it gives me the following error:

ERROR: Can't locate Linux/Ethtool/Settings.pm in @INC (you may need to install the Linux::Ethtool::Settings module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl .) at line 2.
BEGIN failed--compilation aborted at line 2.
DETAIL: 
HINT: 
STATEMENT: CREATE FUNCTION pgcenter.get_netdev_link_settings(INOUT iface CHARACTER VARYING, OUT speed BIGINT, OUT duplex INTEGER) RETURNS RECORD
    LANGUAGE plperlu
    AS $$
    use Linux::Ethtool::Settings;
    if (my $settings = Linux::Ethtool::Settings->new($_[0])) {
      my $if_speed  = $settings->speed();
      my $if_duplex = $settings->duplex() ? 1 : 0;
      return {iface => $_[0], speed => $if_speed, duplex => $if_duplex};
    } else {
      return {iface => $_[0], speed => 0, duplex => -1};
    }
	$$;
![captura de pantalla de 2018-10-03 23-32-45](https://user-images.githubusercontent.com/43837440/46451677-82824580-c765-11e8-9172-b7611c3dd579.png)

**Comment by lesovsky** [comment]
Hi,
this is described in the [docs](https://github.com/lesovsky/pgcenter/blob/master/doc/pgcenter-config-readme.md)

You should resolve the following limitations, before installing schema:
```
Installing and removing functions is possible with pgcenter config, however, with few limitations:

plperlu (which means untrusted plperl) procedural language must be installed manually in the database you want to connect pgCenter to (see details here).
perl module Linux::Ethtool::Settings should be installed in the system, it's used to get speed and duplex of network interfaces and properly calculate some metrics.
```

**Comment by lesovsky** [comment]
In the attached screenshot I have seen you trying to install schema into localhost, it's completely unnecessary -- system stats will be obtained from local /proc filesystem.
Installing schema required if you're trying to connect to *remote* postgres.
