### ISSUE TITLE
ERROR: auth failed

### ISSUE THREAD

**Issue by MichaelDBA** [lesovsky/pgcenter#52]
pgcenter top -h localhost -U postgres -d mydb

```
pgcenter: 2018-12-15 14:59:21, load average: 0.00, 0.00, 0.00                                                         state [failed]: localhost:5432 postgres@iodb (ver: , up , recovery: )
    %cpu:  0.0 us,  0.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st                                        activity:  0/0 conns,  0/0 prepared,  0 idle,  0 idle_xact,  0 active,  0 waiting,  0 others
 MiB mem:      0 total,      0 free,      0 used,        0 buff/cached                                                autovacuum:  0/0 workers/max,  0 manual,  0 wraparound, --:--:-- vac_maxtime
MiB swap:      0 total,      0 free,      0 used,      0/0 dirty/writeback                                            statements:   0 stmt/s, 0.000 stmt_avgtime, --:--:-- xact_maxtime, --:--:-- prep_maxtime

ERROR: auth failed
DETAIL:
HINT:
```
I even have a pgcenterrc file like this:
`localhost:5432:mydb:postgres:mypassword`

I can do psql like this:
`psql -h localhost -U postgres mydb -p 5432`

**Comment by lesovsky** [comment]
Hi, 
1) pgcenterrc file is now used since pgcenter 0.5.0. Auth information can be read from `.pgpass` file, which suitable for psql.
2) Try to connect using unix_socket_dir, for example `pgcenter top -h /var/run/postgresql'. This directory may vary depending on Linux distribution.

**Comment by MichaelDBA** [comment]
using socket dir worked so does it automatically look at .pgpass or do i need to pass that as a -c parameter?

**Comment by lesovsky** [comment]
It looks at .pgpass automatically, it's feature of used db driver.

**Comment by MichaelDBA** [comment]
thanks
