### ISSUE TITLE
pg_stat_statements showing info on other DBs although a DB specified on program launch

### ISSUE THREAD

**Issue by kmoppel** [lesovsky/pgcenter#65]
Thanks for the great tool frist! But when I run "pgcenter top mydb", specifying the DB to be monitored explicilty, still the stat_statements view shows statements from other DBs, making it a bit "crowded". Probably not as intended.

**Comment by lesovsky** [comment]
It's working as intended and basically there was no aim to filter rows for particular databases in pg_stat_statements.
Connecting to particular databases is useful when you would like to see stats about indexes/tables/functions that are stored in postgres in per-database manner.

Anyway filtering is available using `/` hotkey. It is per-column and supports [regexp](https://golang.org/pkg/regexp/).

**Comment by kmoppel** [comment]
@lesovsky ah nice, didn't realize I can use filters for that, no problemo then :)
