### ISSUE TITLE
Need screenshots

### ISSUE THREAD

**Issue by mgalgs** [lesovsky/pgcenter#67]
`pgcenter` sounds like it has a lot of awesome features.  Even so, the UI could make or break it for me...  It would be great to see a few screenshots of the tool in action to avoid having to install and configure it.

**Comment by lesovsky** [comment]
Ok, will think about publishing some gif(s) on readme page.

**Comment by lesovsky** [comment]
fixed in c42a21a1, see gif in main README page

**Comment by mgalgs** [comment]
Fantastic!  Thank you!
