### ISSUE TITLE
DBA

### ISSUE THREAD

**Issue by dbaid** [lesovsky/pgcenter#71]
Hello,

    Try it and get the following errors :
OS: Red Hat Enterprise Linux Server release 5.3 (Tikanga)
Postgres :  EnterpriseDB 9.2.4.8 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-52), 64-bit

runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x824396, 0x17)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/panic.go:774 +0x72
runtime.netpoll(0x15ca54e2b4b07700, 0xdf8475800)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/netpoll_epoll.go:75 +0x229
runtime.sysmon()
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/proc.go:4337 +0x298
runtime.mstart1()
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/proc.go:1201 +0xc3
runtime.mstart()
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/proc.go:1167 +0x6e

goroutine 1 [runnable, locked to thread]:
syscall.readlen(0x9, 0xc00007ca90, 0x8, 0x3, 0xc0000d6000, 0x1b)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/syscall/zsyscall_linux_amd64.go:1025 +0xef
syscall.forkExec(0xc0000922d0, 0x10, 0xc00008a2c0, 0x2, 0x2, 0xc00007cbb0, 0x1a, 0x70b6078700000200, 0xc00005d500)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/syscall/exec_unix.go:210 +0x3c6
syscall.StartProcess(...)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/syscall/exec_unix.go:248
os.startProcess(0xc0000922d0, 0x10, 0xc00008a2c0, 0x2, 0x2, 0xc00007cd48, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/exec_posix.go:51 +0x2b0
os.StartProcess(0xc0000922d0, 0x10, 0xc00008a2c0, 0x2, 0x2, 0xc00007cd48, 0x1a, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/exec.go:102 +0x7c
os/exec.(*Cmd).Start(0xc0000c62c0, 0x6f1601, 0xc0000aa050)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/exec/exec.go:416 +0x50c
os/exec.(*Cmd).Run(0xc0000c62c0, 0xc0000aa050, 0x0)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/exec/exec.go:338 +0x2b
os/exec.(*Cmd).Output(0xc0000c62c0, 0x7, 0xc00007ce50, 0x1, 0x1, 0xc0000c62c0)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/exec/exec.go:540 +0x88
github.com/lesovsky/pgcenter/lib/stat.init.0()
        /home/travis/gopath/src/github.com/lesovsky/pgcenter/lib/stat/stat.go:51 +0x7c

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /home/travis/.gimme/versions/go1.13.1.linux.amd64/src/os/signal/signal_unix.go:29 +0x4

**Comment by lesovsky** [comment]
Hi, you're using quite old version of the operating system and Im not completely sure that I could fix the issue in near time.
Also you're using Postgres 9.2 - vanilla 9.2 version is end of life and is not supported anymore (but I don't know about supporting policy of EnterpriseDB). Most of pgcenter's functions will not work with Postgres 9.2. Despite this issue I strongly recommend you upgrade your postgres.

I think, I could fix the issue related to `lib/stat/stat.go:51 +0x7c`, but proper work with 9.2 is not guaranteed, sorry.

**Comment by mjtrangoni** [comment]
@lesovsky Golang is not supporting RHEL5, see [here](https://golang.org/dl/).

> Linux 2.6.23 or later

**Comment by lesovsky** [comment]
@mjtrangoni thanks

@dbaid you can also check that in install [notes ](https://golang.org/doc/install#requirements)
> CentOS/RHEL 5.x not supported.

**Comment by dbaid** [comment]
Running on 6.4 with EDB 9.3 is ok.
Thank you!!
<img width="960" alt="pgcenter_top" src="https://user-images.githubusercontent.com/47732154/66197264-9dff9380-e6cc-11e9-8a87-f32db3480a8b.png">
