### ISSUE TITLE
query report cannot be generated - error 'No stats for such queryid'

### ISSUE THREAD

**Issue by demonfoxkzn** [lesovsky/pgcenter#74]
if I request query report from pg_stat_statements mode (with shift+G) and provide query from queryid column it returns 'No stats for such queryid'
I opened source code and I suppose found reason of such error:
to generate queryid in pg_stat_statements mode it uses this query
eft(md5(p.dbid::text || p.userid || p.queryid), 10)
but to find query in  in query report mode it uses 
left(md5(d.datname || a.rolname || left(p.query, 128)), 10)

**Comment by lesovsky** [comment]
Hi, this query has been fixed in dev branch 7bd2d79
It seemed to me I already merged that (( Will merge it soon.

**Comment by lesovsky** [comment]
merged into v0.6.5
