### ISSUE TITLE
ERROR: failed connection establishing: pq: unknown authentication response: 10

### ISSUE THREAD

**Issue by SleepyR** [lesovsky/pgcenter#77]
The error occurred when connecting to a PostgreSQL server with a parameter password_encryption= scram-sha-256. The authentification method in pg_hba is also configured as scram-sha-256.
OS : CentOS Linux release 7.8.2003 (Core)
PSQL: PostgreSQL 10.13 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

Note: We faced the same error on another application and it was resolved by updating the JDBC Driver.

![picturemessage_urqfcjgh awn](https://user-images.githubusercontent.com/31797437/86386330-a65c1d80-bca2-11ea-8da2-e4f9867015e6.png)

**Comment by kakoni** [comment]
@lesovsky Perhaps libpq should be updated to v1.8?

**Comment by SleepyR** [comment]
How can we check the version of the libpq?

**Comment by ImreSamu** [comment]
> Perhaps libpq should be updated to v1.8?

this Docker code fragment ( with GO environment ) is solved my  `scram-sha-256` connection problem ,

on the other hand:
(in my test environment; `go1.15.3` ) there are some problems with the `go test all`
....  so need some debugging .. , don't use my workaround blindly ! 

```
RUN git clone --depth 1 --branch master https://github.com/lesovsky/pgcenter \
    && cd pgcenter \
    && go get -u github.com/lib/pq@v1.8.0 \
    && make \
    && make install \
    && pgcenter --version
```

**Comment by lesovsky** [comment]
Pgcenter moved from lib/pq to pgx. I've tested latest pgcenter 0.9.2 with configured scram-sha-256 auth and found no errors.

Close the issue, but if someone is still facing with scram-sha-256 auth errors, feel free to re-open and describe details.
