### ISSUE TITLE
Unable generate report

### ISSUE THREAD

**Issue by foxipub** [lesovsky/pgcenter#78]
Postgre version 11.7

1.First i record statistic file:

./pgcenter record -U postgres pkpsmrdb

2.Then i try to buil report from file and get:

[root@ip-172-27-9-56 pgcenter]# ./pgcenter report -D
INFO: reading from pgcenter.stat.tar
INFO: report pg_stat_database
INFO: start from: 0001-01-01 00:00:00 +0000 UTC, end at: 2020-07-24 18:57:06 +0000 UTC, delta interval: 1s
2020/07/24 18:57:06 failed diff on pg_stat_database.20200724T184455.json: failed to convert to integer [0:16]: strconv.ParseInt: parsing "": invalid syntax
[root@ip-172-27-9-56 pgcenter]#

**Comment by lesovsky** [comment]
Hi, could you share a tar file, to let me inspect it?

**Comment by foxipub** [comment]
[pgcenter.stat.zip](https://github.com/lesovsky/pgcenter/files/4973935/pgcenter.stat.zip)
Hello Alexey, hope its uploaded as it about 50 mb but i already try to reduce collection with -c flag and have got same result.

**Comment by lesovsky** [comment]
@foxipub 

Hi, new version v0.7.0 released where lot of changes have been made. Unfortunately, backward compatibility is broken and new version cannot read stat files created by old version.

Could you try to reproduce the bug.

**Comment by lesovsky** [comment]
Closed due to inactivity.
