### ISSUE TITLE
Не работает горячая клавиша 'v'

### ISSUE THREAD

**Issue by loukash** [lesovsky/pgcenter#79]
При нажатии 'v' ничего не происходит.

```
pgcenter v0.6.5 89be232-master
Debian 7.2
PostgreSQL 9.6.5
```

**Comment by lesovsky** [comment]
вакумная статистика перенесена на клавишу 'p', там можно нажимать ее несколько раз чтобы переключаться между несколькими 'pg_stat_progress_' вьюхами. Либо через 'P' вывести меню и выбрать нужное. Во встроенной справке это отражено, но упоминание 'v' клавиши забыл удалить просто.
