### ISSUE TITLE
Compile problem on Debian 6

### ISSUE THREAD

**Issue by bmomjian** [lesovsky/pgcenter#8]
I am on Debian 6/Squeeze, and I get this error on the compile:

cc -g -std=gnu99 -Wall -pedantic -I/usr/local/pgsql/include -L/usr/local/pgsql/lib -o pgcenter pgcenter.c -L/usr/lib -lncurses -lmenu -lpq
pgcenter.c: In function ‘get_speed_duplex’:
pgcenter.c:1701: error: ‘DUPLEX_UNKNOWN’ undeclared (first use in this function)
                                       ---------------------------

**Comment by lesovsky** [comment]
Hi,
DUPLEX_UNKNOWN should be defined in /usr/include/linux/ethtool.h. Try to install linux-libc-dev and repeat make.

**Comment by bmomjian** [comment]
On Sat, Dec 19, 2015 at 09:43:48AM -0800, Lesovsky Alexey wrote:
> Hi,
> DUPLEX_UNKNOWN should be defined in /usr/include/linux/ethtool.h. Try to
> install linux-libc-dev and repeat make.

I have that file, and it has these defines:

	/* Duplex, half or full. */
	#define DUPLEX_HALF     0x00
	#define DUPLEX_FULL     0x01

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I. As I am, so you will be. +
+ Roman grave inscription                             +

**Comment by lesovsky** [comment]
Ok, I add DUPLEX_UNKNOWN in pgcenter.h (6238e43). Pull changes and try make again.

**Comment by bmomjian** [comment]
On Sat, Dec 19, 2015 at 10:02:25AM -0800, Lesovsky Alexey wrote:
> Ok, I add DUPLEX_UNKNOWN in pgcenter.h (6238e43). Pull changes and try make
> again.

Yes, that fixed it and it compiled just fine.

I noticed there is no default directory for the host, e.g. /tmp.  I used
'-h /tmp' to get it started and connected.  Thanks.

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I. As I am, so you will be. +
+ Roman grave inscription                             +

**Comment by lesovsky** [comment]
Default directory not used because it causes connections problems on different linux distros (because libpq compiled with different defaults, e.g. rhel/centos uses /tmp, and newer debian/ubuntu uses /var/lib/postgresql.). If "host" variable not specified at startup, this var obtained from libpq defaults.

**Comment by bmomjian** [comment]
On Sat, Dec 19, 2015 at 10:28:58AM -0800, Lesovsky Alexey wrote:
> Default directory not used because it causes connections problems on different
> linux distros (because libpq compiled with different defaults, e.g. rhel/centos
> uses /tmp, and newer debian/ubuntu uses /var/lib/postgresql.). If "host"
> variable not specified at startup, this var obtained from libpq defaults.

OK, sounds good.

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I. As I am, so you will be. +
+ Roman grave inscription                             +
