### ISSUE TITLE
Cannot connect via Unix socket not specifying it explicitly, while psql can do it

### ISSUE THREAD

**Issue by NikolayS** [lesovsky/pgcenter#80]
Hi, noticed that on Debian/Ubuntu, `psql -U postgres postgres` works, while `pgcenter top -U postgres postgres` doesn't -- until I specify Unix socket directory explicitly: 

```
pgcenter top -U postgres postgres -h /var/run/postgresql
```
-- this works well

**Comment by lesovsky** [comment]
pgcenter has been installed from [releases](https://github.com/lesovsky/pgcenter/releases) or compiled manually?

**Comment by lesovsky** [comment]
@NikolayS 
Try it with v0.7.0, in this release lib/pq driver has been replaced with jackc/pgx and behavior could change.
I also tested on:
- Ubuntu 20.04
- postgres:13.2 (official Postgres Docker image based on Debian Buster)

In both cases could connect without specifying extra opts.

**Comment by lesovsky** [comment]
Closed due to inactivity.
