### ISSUE TITLE
pgcenter top SSL is not enabled on the server, connecting with sslmode=disable

### ISSUE THREAD

**Issue by vitalroot** [lesovsky/pgcenter#81]
Linux xxx 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Tue Oct 20 12:33:57 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
pgcenter top 
SSL is not enabled on the server, connecting with sslmode=disable
ERROR: failed connection establishing: pq: Ident authentication failed for user "postgres"

**Comment by lesovsky** [comment]
It just looks like you cannot connect to your db server. Try to use -h, -p, -U, -d, and specify exact connection parameters.
