### ISSUE TITLE
error git checkout

### ISSUE THREAD

**Issue by shab2** [lesovsky/pgcenter#84]
Алексей, добрый день
В git пока не силен. Не могу оценить, из-за чего ошибка

git clone https://github.com/lesovsky/pgcenter
cd pgcenter
git checkout --track origin/dev
fatal: 'origin/dev' is not a commit and a branch 'dev' cannot be created from it

**Comment by lesovsky** [comment]
The 'dev' branch is not exist,  Build from master branch.
Also there is packages available in [releases](https://github.com/lesovsky/pgcenter/releases) page.
