### ISSUE TITLE
var PGPORT dont used

### ISSUE THREAD

**Issue by shab2** [lesovsky/pgcenter#85]
Hi, Alexey

<runing successful>

[PCFT]$ pgcenter top --port=5434 pcft
SSL is not enabled on the server, connecting with sslmode=disable

<runing not successful>

[PCFT]$ echo $PGPORT
5434
[PCFT]$ pgcenter top pcft
ERROR: failed connection establishing: dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by lesovsky** [comment]
Confirmed, thanks. Will fix it in 'refactoring' branch.

**Comment by lesovsky** [comment]
@shab2 fixed in v0.7.0.
The cause was port option was overwritten by cmd defaults.
