### ISSUE TITLE
Timing Statements query error 

### ISSUE THREAD

**Issue by AndreyKopeyko** [lesovsky/pgcenter#88]
**Describe the bug**
pgcenter fails to show timing statistics after 12.6 -> 13.2 PostgreSQL upgrade. I've tried 0.6.4 an 0.8.0 RPM packages - the same result :-(

```ERROR: column p.total_time does not exist ```

**Environment**
Describe the environment where the bug occurred.
- OS: CentOS Linux 7 (Core) 
- pgCenter Version:
  pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release
- pgCenter installation method: RPM from releases page
- PostgreSQL Version:
  PostgreSQL 13.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**To Reproduce**
Simple press 'x' button and you'll see 
![screenshot](http://dev2.kopeyko.ru/tmp/Screenshot_2021-03-10T17-16-41.png)

All extensions were upgraded too after PGSQL upgrade itself.
```sync=# \dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description                               
--------------------+---------+------------+------------------------------------------------------------------------
 pg_stat_statements | 1.8     | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

sync=# 
```

Dropping the extension and re-creating it - does not help.

**Expected behavior**
Usually it shows the timing stat table

**Additional context**
Not this time.

**Comment by AndreyKopeyko** [comment]
Seems it is caused by column renaming in PGSQL-13

12   |  13 
total_time -> total_exec_time
min_time -> min_exec_time
max_time -> max_exec_time
mean_time -> mean_exec_time
stddev_time -> stddev_exec_time

see https://postgrespro.ru/docs/postgresql/13/pgstatstatements?lang=en

**Comment by lesovsky** [comment]
Thanks for report,
it seems pgcenter uses wrong version of pg_stat_statements query. Will check that soon.

**Comment by lesovsky** [comment]
Hmm, tried to reproduce on `centos:7` docker image with postgresql13 from pgdg repo and found no problems, tried the different cases including superuser and unprivileged user. Sounds weird, I know ))

Could you show the following info:
- output of `SELECT current_setting('server_version'), current_setting('server_version_num')::int;`.

I know it might sounds strange, but make sure you really run `v0.8.0` against Postgres 13. Don't try versions `0.6.x` - they will not work, because it don't support new pg_stat_statements.

**Comment by lesovsky** [comment]
Commands output looks good.

1. Is there any errors in Postgres log related to pgcenter activity?

2. Could you watch on statements stats in top-right corner? Do the numbers change over time or they are always zeroes?

![issue-88-img](https://user-images.githubusercontent.com/953312/110672755-ce1c6180-81f1-11eb-8c1a-ce44d46034b8.png)

3. Also, could inspect your schema related to pg_stat_statements? Is there any grants on schema, view or something that might restrict access to the pg_stat_statements (security or audit modules)?

**Comment by AndreyKopeyko** [comment]
Sorry, it all my mistake - mainly because of a hurry I installed 0.8.0 package manually not waiting it to be deployed on local mirror. And because the package places the binary into another place the old one was kept, and that one was launched for 'postgres' user

    [user@db-t1 pgsql]# sudo -u postgres which pgcenter 
    /bin/pgcenter
    [user@db-t1 pgsql]#

Sorry for bothering you, Alexey.

Can you please for next releases put binary in common for RH place "/bin/pgcenter"?
Would it be so for 0.8.0 also, this stupid mistake will definitely have no chances to happen.

**Comment by lesovsky** [comment]
I also confused to understand why it is not working as expected. 
I'm not familiar with RH specifics and use defaults settings provided by `goreleaser` which build packages. If it allows to specify exact paths I will try to adjust them in next releases.
