### ISSUE TITLE
Doesn't work with PostgreSQL built manually from source

### ISSUE THREAD

**Issue by afiskon** [lesovsky/pgcenter#9]
## Steps to reproduce

1. Create a new Ubuntu 14.04 LTS VM or LXC container
2. Build PostgreSQL from source according to official documentation (it's easy!): `./configure --enable-tap-tests --enable-debug && make clean && make -j8 && make check && sudo make install`

3. Use this init.d script to start a service: https://github.com/afiskon/postgresql-initd

4. Install pgcenter
5. Run `pgcenter postgres`

## Expected result:

Nice picture like this: http://blog.postgresql-consulting.com/2015/12/pgcenter-020-released.html

## Actual result:

Something like this http://i.imgur.com/Wpv9aUl.png

```
The connection to the server was lost. Attempting reconnect.
FATAL: no connection to the server
ERROR: Connection to : with postgres@postgres failed.
```

**Comment by lesovsky** [comment]
Hi, 
try to specify detailed connection settings, for example: pgcenter -h 127.0.0.1 postgres
Also, see pgcenter -h.

**Comment by afiskon** [comment]
I tried, read man, edited pg_hba.conf and restarted PostgreSQL - nothing helped.

**Comment by lesovsky** [comment]
Run 'netstat -luntp |grep postgres' and see results.

**Comment by afiskon** [comment]
```
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      17850/postgres
```

**Comment by lesovsky** [comment]
Ok, let's try 'pgcenter -h 127.0.0.1 -p 5432 -U postgres postgres', and show program screenshot, or show "conn1" string content (up-right corner).

**Comment by afiskon** [comment]
Now it seems to work http://i.imgur.com/ua7EV6F.png >_>

**Comment by lesovsky** [comment]
Good!

**Comment by afiskon** [comment]
It was obviously my mistake, I should read --help more carefully before reporting a bug. Thanks for your help and a great tool!
