### ISSUE TITLE
Problem running  pgcenter record -1

### ISSUE THREAD

**Issue by artasheskhachatryan1991** [lesovsky/pgcenter#90]
I get following error "ERROR: column "wal_bytes" does not exist (SQLSTATE 42703)"
when run "pgcenter record -1 -U postgres".

My postgres version is
PostgreSQL 12.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

And pgcenter version is 
pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release

**Comment by lesovsky** [comment]
Hi, thanks for report. Error has been reproduced and will be fixed soon.

**Comment by lesovsky** [comment]
The issue has been fixed in master branch (1126a16). In deb/rpm packages it will be fixed in next release.
