### ISSUE TITLE
pgcenter v0.8.0 "total_exec_time" does not exist

### ISSUE THREAD

**Issue by makeconfig2017** [lesovsky/pgcenter#98]
**Describe the bug**
Error while running pgcenter: ERROR: column "total_exec_time" does not exist (SQLSTATE 42703)

**Environment**
Describe the environment where the bug occurred.
- OS: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
  
- pgCenter Version [pgcenter v0.8.0 df1cea5201ee10e6a9b99fae6a45bc5a3a4f70b4-release]
- pgCenter installation method: [https://github.com/lesovsky/pgcenter/releases/tag/v0.8.0]
- PostgreSQL Version [13.3]

**To Reproduce**
pgcenter top

**Expected behavior**
Run pgcenter

**Comment by lesovsky** [comment]
Check pg_stat_statements version in the database. Seems it is outdated (should be 1.8).

**Comment by makeconfig2017** [comment]
Thank you very much ! It was updated PostgreSQL with earlier installed pg_stat_statements.
drop extension pg_stat_statements;
create extension pg_stat_statements;
And it works !
